<!-- Universal Analytics Start -->
<?php $helper = Mage::helper('baua') ?>
<?php if($helper->isActive()): ?>
     <script type="text/javascript">

         (window.gaDevIds=window.gaDevIds||[]).push('B7gQME');

         (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
         (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
         m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
         })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
         <?php $accounts = $helper->getAccounts(); ?>
         <?php foreach ($accounts as $account): ?>
             ga('create', '<?php echo $account['trackingID'] ?>','auto', {'name': '<?php echo $account['name']; ?>'});
             ga('<?php echo $account['name']; ?>.require', 'ec');
             ga('<?php echo $account['name']; ?>.require', 'displayfeatures');

             <?php echo $helper->generateCurrencyInit($account['name']) ?>
             <?php echo $helper->generateProductImpressions($account['name']) ?>
             <?php echo $helper->generatePromoImpressions($account['name']) ?>
             <?php echo $helper->getAction() ?>
             ga('<?php echo $account['name']; ?>.send', 'pageview');
         <?php endforeach; ?>

         <?php echo $helper->generateProductClickEvents($accounts) ?>
         <?php echo $helper->generatePromoClickEvents($accounts) ?>
    </script>
<?php endif ?>
<!-- Universal Analytics End -->
