<!-- Universal Analytics Order Success -->
<?php $this->JS = Mage::getSingleton('baua/js'); ?>
<?php $order = Mage::getModel('sales/order')->loadByIncrementId(Mage::getSingleton('checkout/session')->getLastRealOrderId()); ?>
<?php $_helper = Mage::helper('baua') ?>
<?php $data = Mage::getModel('baua/monitor')->generateTransactionData($order); ?>
<?php $productArray[] = array(); ?>
<?php $accounts = $_helper->getAccounts(); ?>

<?php foreach ($order->getAllVisibleItems() as $item) :?>
    <?php $result = Mage::getModel('baua/monitor')->generateProductData($item); ?>
    <?php if($result != null) : ?>
        <?php foreach ($accounts as $account): ?>
            <?php $productArray[] = $this->JS->generateGoogleJS($account['name'].'.ec:addProduct', $result) . "\n"; ?>
        <?php endforeach; ?>
    <?php endif; ?>
<?php endforeach; ?>


<?php if($_helper->isActive()): ?>
    <script type="text/javascript">
        <?php foreach($productArray as $product) : ?>
            <?php if(!is_array($product)) : ?>
                <?php echo $product; ?>
            <?php endif; ?>
        <?php endforeach; ?>
        <?php foreach ($accounts as $account): ?>
            <?php echo $this->JS->generateGoogleJS($account['name'].'.ec:setAction', 'purchase', $data) . "\n"; ?>
            <?php echo $this->JS->generateGoogleJS($account['name'].'.send', 'pageview')?>
        <?php endforeach; ?>
    </script>
<?php endif ?>
<!-- Universal Analytics Order Success End -->
